mailing_service/mailing/urls.py
from django.urls import path

from . import views
from .views import ConsumerList, ConsumerDetail, MailingList, MailingDetail

app_name = 'mailing'

urlpatterns = [
    path('', views.index, name='index'),
    # Создание записи
    path('mailing/create/', views.mailing_create, name='mailing_create'),
    path('api/consumer/', ConsumerList.as_view()),
    path('api/consumer/<int:pk>/', ConsumerDetail.as_view()),
    path('api/mailing/', MailingList.as_view()),
    path('api/mailing/<int:pk>/', MailingDetail.as_view()),
]

mailing_service/mailing_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('rest_framework.urls')),
]

mailing_service/mailing/models.py
from django.db import models
from taggit.managers import TaggableManager

from .validators import validate_phone_number


class Consumer(models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=11, validators=[validate_phone_number])
    # Плохое представление о трех полях ниже и их своиствах и назначения
    provider_code = models.CharField(max_length=20)
    tags = TaggableManager()
    time_zone = models.IntegerField()

    def __str__(self):
        return self.name


class Message(models.Model):
    create_date = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Время отправки')
    is_sent = models.BooleanField()
    consumer = models.ForeignKey(Consumer,
                                 on_delete=models.CASCADE,
                                 related_name='messages',
                                 verbose_name='Пользователь')

    def __str__(self):
        return f'Message id={self.pk} to {self.consumer.name}'


class Mailing(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    text = models.TextField(verbose_name='Сообщение')
    start_date = models.DateTimeField(auto_now_add=False,
                                      verbose_name='Время старта')
    finish_date = models.DateTimeField(auto_now_add=False,
                                       verbose_name='Время завершения')
    messages = models.ManyToManyField(Message,
                                      blank=True,
                                      null=True,
                                      related_name='mailings',
                                      verbose_name='Сщщбщения')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']

mailing_service/mailing/forms.py
from django import forms
from django.forms import ModelForm

from .models import Mailing


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        fields = ('text', 'start_date', 'finish_date')

mailing_service/mailing/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from rest_framework import generics
from rest_framework.response import Response
import requests

from .forms import MailingForm
from .models import Mailing, Consumer, Message
from .serializers import ConsumerSerializer, MailingSerializer


def index(request):
    template = 'mailing/index.html'
    mailing_list = Mailing.objects.all()
    paginator = Paginator(mailing_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def mailing_create(request):
    # Проверяем, получен POST-запрос или какой-то другой:
    if request.method == 'POST':
        form = MailingForm(request.POST)
        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.save()
            return redirect('mailing:index')
        return render(request, 'mailing/create_mailing.html', {'form': form})
    form = MailingForm()
    context = {
        'form': form
    }
    return render(request, 'mailing/create_mailing.html', context)


# DRF


class ConsumerList(generics.ListCreateAPIView):
    queryset = Consumer.objects.all()
    serializer_class = ConsumerSerializer


class ConsumerDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Consumer.objects.all()
    serializer_class = ConsumerSerializer


class MailingList(generics.ListCreateAPIView):
    queryset = Mailing.objects.all()
    serializer_class = MailingSerializer

    def perform_create(self, serializer):
        # Работу со временем я не стал пробовать,
        # потому что как сделать чтобы запрос ожидал не знаю вообще,
        # наверное это что-то связанное с ассинхроностью, тьма
        # сделал отправку запроса как смог.
        # Со статистико тоже мало что понял
        for m_id in serializer.data.get('messages'):
            message_to_send = Message.objects.get(id=m_id)
            if not message_to_send.is_sent:
                data = {
                    "id": m_id,
                    "phone": int(message_to_send.consumer.phone_number),
                    "text": serializer.data.get('text'),
                }
                response = requests.post(f'https://probe.fbrq.cloud/v1/send/{m_id}', json=data, headers={
                    'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzg5NjU0ODUsImlzcyI6ImZhYnJpcXVlIiwibmFtZSI6IkJhcmkifQ.rADn5-Eg7EipxwlGyQ5RimDUzJU3pKjFNIn7SITaBGo'
                })
                if response.status_code == 200:
                    message_to_send.is_sent = True
                    message_to_send.save()
        return Response(status=201)


class MailingDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Mailing.objects.all()
    serializer_class = MailingSerializer

mailing_service/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Mailing service
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="page-footer font-small blue border-top">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

mailing_service/templates/includes/article.html
<ul>
  <li>
    ID: {{ obj.pk }}
  </li>
  <li>
    Время начала отправки: {{ obj.start_date|date:"r" }}
  </li>
  <li>
    Время завершения отправки: {{ obj.finish_date|date:"r" }}
  </li>
</ul>
<h5>Текст</h5>
<p>
  {{ obj.text }}
</p>

mailing_service/templates/includes/footer.html
{% load static %}
<div class="footer-copyright text-center py-3">© {{ year }} Copyright
  <p>Mailing service</p>
</div>

mailing_service/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: #2da6f5">
  <div class="container">
    <h3>Сервис рассылок</h3>
      <div>
        <a href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
      </div>
  </div>
</nav>

mailing_service/templates/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{# Отрисовываем навигацию паджинатора только если все посты не помещаются на первую страницу #}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

mailing_service/templates/mailing/create_mailing.html
{% extends 'base.html' %}
{% block title %}
  Добавить пост
{% endblock %}
{% block content %}
  <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Добавить пост
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'mailing:mailing_create' %}">{% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    {{form.text}}
                    Время старта(гггг-мм-дд чч: мм: сс)
                    {{form.start_date}}
                    Время завершения(гггг-мм-дд чч: мм: сс)
                    {{form.finish_date}}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

mailing_service/templates/mailing/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container py-5">
    <h1>Все рассылки</h1><br>
    {% for obj in page_obj %}
      <article>
        {% include 'includes/article.html' %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}